Upgrade Rails version 4 to 5 and bootstrap version 3 to v4.alpha
iogbole/gentelella_on_rails pull request #16
Opened 2016-12-12 05:57 UTC by ggomagundan

1. Upgrade rails version
- Rails4 => Rails 5.0

2. Upgrade Bootstrap Version
- Bootstrap v3 => Bootstrap v4.alpha

 3. Change Root Path
- plainpage#index  => plainpage#dashborad

4. Update Gentelella Version
- update Gentelella version and update vendor files

2016-12-14 13:35 UTC, PeterTeng requested changes
I just made some reviews😬

I think it is better to separate the pull request in each features

By each feature should provide the reason of changes.

2016-12-14 13:35 UTC, PeterTeng commented on Gemfile
> +  gem 'web-console', '~> 3.0'
This is the sample project for Gentelella only.
It's better to just add necessary Gems

2016-12-14 13:35 UTC, PeterTeng commented on Gemfile.copy
> +source 'https://rubygems.org'
What is this file stands for?

Too many comment outs🤔

2016-12-14 13:35 UTC, PeterTeng commented on Gemfile
> +gem 'bootstrap', '~> 4.0.0.alpha5'
I think gentelella is not using bootstrap above version 4.x🤔

2016-12-15 02:34 UTC, ggomagundan commented on Gemfile.copy
> +source 'https://rubygems.org'
@PeterTeng  Oh, This is my mistake :( , I Committing remove this file

2016-12-15 02:44 UTC, ggomagundan commented on Gemfile
> +gem 'bootstrap', '~> 4.0.0.alpha5'
@PeterTeng  Now, I downgrade Bootstrap Version 3 :) Thx to your Reviews

2016-12-15 05:07 UTC, ggomagundan commented
After Review

- Remove `Gemfile.copy` File (For Reference Rails5 Project Gemfile )
- Change stylesheet mismatch path
- Remove duplicate `require` line ( duplicate add `js/custom.js` file)

2022-02-14 06:51 UTC, closed without merging